### ISSUE TITLE
Doesn't work in Samsung mobile browser

### ISSUE THREAD

**Issue by crystal13282** [silktide/cookieconsent2#14] opened 2015-06-11 12:22 UTC
Hello,

the cookies consent doesn't appear in samsung mobile browser (smartphone Samsung I9100).
So I tried Google Chrome browser and it works.

I hope you can solve,

thank you a lot for your script!
Gianfranco

**Comment by ValBK** [comment] 2015-09-28 08:24
Hello, First off all thank you for the script.
I have the same problem. cookie consent does not apear on mobile site(on desktop version work fine)
(I am not a coder, I make 2 Column Responsive Layout with HTML and CSS. I followed wizard, and put the code before /head tag.  Am I doing something wrong? 
Is there something to do in css or html?

**Comment by oliveremberton** [comment] 2015-11-24 12:39
Possible duplicate of https://github.com/silktide/cookieconsent2/issues/62

**Closed by oliveremberton** 2015-11-24 12:39 UTC
