### ISSUE TITLE
Cookie Consent doesn't work on mobile browser

### ISSUE THREAD

**Issue by dgmerino** [silktide/cookieconsent2#122] opened 2016-02-27 12:23 UTC
Hello!
I've install the plugin in my web and works very well in IE and in Chrome, but when I tried it in my smart phone, it didn't work in the samsung usual navigator.
My phone is a samsung galaxy

**Comment by Dolondro** [comment] 2016-03-14 23:25
Duplicate of #62

**Closed by Dolondro** 2016-03-14 23:25 UTC
Labels: duplicate
